// <auto-generated />
using System;
using LodgingReservation_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LodgingReservation_BE.Migrations
{
    [DbContext(typeof(LodgingReservationDbContext))]
    [Migration("20260820081346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LodgingReservation_BE.Models.ExtraService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EXTRA_SERVICE_NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UNIT_TYPE");

                    b.HasKey("Id");

                    b.ToTable("EXTRA_SERVICE");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AMOUNT_PAID");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("INVOICE_NUMBER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("RESERVATION_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ReservationId");

                    b.ToTable("PAYMENT");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DISCOUNT_PERCENTAGE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PROMO_CODE");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VALID_UNTIL");

                    b.HasKey("Id");

                    b.HasIndex("PromoCode")
                        .IsUnique();

                    b.ToTable("PROMOTION");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AddOnsTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ADD_ONS_TOTAL");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("BOOKING_CODE");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CHECK_IN_DATE");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CHECK_OUT_DATE");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("GRAND_TOTAL");

                    b.Property<decimal>("LateCheckoutFee")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("LATE_CHECK_OUT_FEE");

                    b.Property<decimal>("PromoDiscount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("PROMO_DISCOUNT");

                    b.Property<long?>("PromotionId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("PROMOTION_ID");

                    b.Property<long?>("ReservationRoomId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RoomSubtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ROOM_SUB_TOTAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("STATUS");

                    b.Property<int>("TotalNights")
                        .HasColumnType("integer")
                        .HasColumnName("TOTAL_NIGHTS");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("PromotionId");

                    b.HasIndex("ReservationRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.ReservationAddOn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExtraServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("EXTRA_SERVICE_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("RESERVATION_ID");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExtraServiceId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationAddOns");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.ReservationRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("PRICE_PER_NIGHT");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("RESERVATION_ID");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("ROOM_ID");

                    b.Property<decimal>("TotalRoomCost")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("TOTAL_ROOM_COST");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.ToTable("ReservationRooms");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ROOM_NUMBER");

                    b.Property<long>("RoomTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ROOM_TYPE_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("ROOM");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.RoomType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("BASE_PRICE");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("CAPACITY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ROOM_TYPE_NAME");

                    b.HasKey("Id");

                    b.ToTable("ROOM_TYPE");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAMA");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USER");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Payment", b =>
                {
                    b.HasOne("LodgingReservation_BE.Models.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Reservation", b =>
                {
                    b.HasOne("LodgingReservation_BE.Models.Promotion", "Promotion")
                        .WithMany("Reservations")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LodgingReservation_BE.Models.ReservationRoom", null)
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationRoomId");

                    b.HasOne("LodgingReservation_BE.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.ReservationAddOn", b =>
                {
                    b.HasOne("LodgingReservation_BE.Models.ExtraService", "ExtraService")
                        .WithMany("ReservationAddOns")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LodgingReservation_BE.Models.Reservation", "Reservation")
                        .WithMany("ReservationAddOns")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraService");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.ReservationRoom", b =>
                {
                    b.HasOne("LodgingReservation_BE.Models.Reservation", "Reservation")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LodgingReservation_BE.Models.Room", "Room")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Room", b =>
                {
                    b.HasOne("LodgingReservation_BE.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.ExtraService", b =>
                {
                    b.Navigation("ReservationAddOns");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Promotion", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationAddOns");

                    b.Navigation("ReservationRooms");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.ReservationRoom", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.Room", b =>
                {
                    b.Navigation("ReservationRooms");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("LodgingReservation_BE.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
